services:
  loadbalancer:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./frontend:/service/frontend
  core-service:
    build:
      context: .
      dockerfile: Dockerfile-core
  math-service:
    build:
      context: .
      dockerfile: Dockerfile-math